src/main/java/kr/co/imguru/TestClass.java

feat: 연동이 제대로 이루어졌는지를 확인하기 위한 테스트 클래스 작성

---

src/main/java/kr/co/imguru/domain/guru/controller/GuruInfoRestController.java
src/main/java/kr/co/imguru/domain/guru/dto/GuruInfoCreateDto.java
src/main/java/kr/co/imguru/domain/guru/dto/GuruInfoReadDto.java
src/main/java/kr/co/imguru/domain/guru/dto/GuruInfoUpdateDto.java
src/main/java/kr/co/imguru/domain/guru/entity/GuruInfo.java
src/main/java/kr/co/imguru/domain/guru/repository/GuruInfoRepository.java
src/main/java/kr/co/imguru/domain/guru/service/GuruInfoService.java
src/main/java/kr/co/imguru/domain/guru/service/GuruInfoServiceImpl.java

1. GuruInfo CRUD 완료
2. Postman으로 테스트 완료

IG-4-kjh/guruinfo - CRUD

---

src/main/java/kr/co/imguru/domain/guru/controller/GuruInfoRestController.java
src/main/java/kr/co/imguru/domain/guru/repository/GuruInfoRepository.java
src/main/java/kr/co/imguru/domain/guru/service/GuruInfoService.java
src/main/java/kr/co/imguru/domain/guru/service/GuruInfoServiceImpl.java
src/main/java/kr/co/imguru/global/model/ResponseStatus.java

IG-7-kjh/guruInfo-refactor

---

src/main/java/kr/co/imguru/domain/member/repository/MemberRepository.java
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/domain/message/controller/MessageController.java
src/main/java/kr/co/imguru/domain/message/dto/MessageCreateDto.java
src/main/java/kr/co/imguru/domain/message/dto/MessageMemberDto.java
src/main/java/kr/co/imguru/domain/message/dto/MessageReadDto.java
src/main/java/kr/co/imguru/domain/message/entity/Message.java
src/main/java/kr/co/imguru/domain/message/repository/MessageRepository.java
src/main/java/kr/co/imguru/domain/message/service/MessageService.java
src/main/java/kr/co/imguru/domain/message/service/MessageServiceImpl.java
src/main/java/kr/co/imguru/domain/post/controller/PostRestController.java
src/main/java/kr/co/imguru/domain/post/dto/PostCreateDto.java
src/main/java/kr/co/imguru/domain/post/dto/PostReadDto.java
src/main/java/kr/co/imguru/domain/post/dto/PostUpdateDto.java
src/main/java/kr/co/imguru/domain/post/entity/Post.java
src/main/java/kr/co/imguru/domain/post/repository/PostRepository.java
src/main/java/kr/co/imguru/domain/post/service/PostService.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java
src/main/java/kr/co/imguru/domain/skill/controller/SkillRestController.java
src/main/java/kr/co/imguru/domain/skill/repository/SkillRepository.java
src/main/java/kr/co/imguru/domain/skill/service/SkillService.java
src/main/java/kr/co/imguru/domain/skill/service/SkillServiceImpl.java
src/main/java/kr/co/imguru/global/model/ResponseStatus.java

1. Post CRUD
2. Message CRUD
3. Skill 쪽에 CRUD 시 파라미터를 skillName으로 했는데, 관리자만 CRUD하기에 SkillId로 해줘도 상관없을 것 같아 수정
4. ResponseStatus에 Exception에 맞는 응답 코드 추가
5. Member, Skill Service 쪽에 Transactional 어노테이션 추가

IG-6-jsh/post,message - CRUD

---

src/main/java/kr/co/imguru/domain/review/controller/ReviewRestController.java
src/main/java/kr/co/imguru/domain/review/dto/ReviewCreateDto.java
src/main/java/kr/co/imguru/domain/review/dto/ReviewReadDto.java
src/main/java/kr/co/imguru/domain/review/dto/ReviewUpdateDto.java
src/main/java/kr/co/imguru/domain/review/entity/Review.java
src/main/java/kr/co/imguru/domain/review/repository/ReviewRepository.java
src/main/java/kr/co/imguru/domain/review/service/ReviewService.java
src/main/java/kr/co/imguru/domain/review/service/ReviewServiceImpl.java
src/main/java/kr/co/imguru/global/model/ResponseStatus.java

1. Review CRUD
2. ReponseStatus 에 Exception 발생 시 필요한 StatusCode 추가

IG-9-jsh/review - CRUD

---

src/main/java/kr/co/imguru/domain/reply/controller/ReplyRestController.java
src/main/java/kr/co/imguru/domain/reply/dto/ReplyCreateDto.java
src/main/java/kr/co/imguru/domain/reply/dto/ReplyReadDto.java
src/main/java/kr/co/imguru/domain/reply/dto/ReplyUpdateDto.java
src/main/java/kr/co/imguru/domain/reply/entity/Reply.java
src/main/java/kr/co/imguru/domain/reply/repository/ReplyRepository.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyService.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyServiceImpl.java
src/main/java/kr/co/imguru/global/model/ResponseStatus.java

IG-8-kjh/reply - CRUD

---

src/main/java/kr/co/imguru/domain/like/repository/LikePostRepository.java
src/main/java/kr/co/imguru/domain/like/repository/LikePostSearchRepository.java
src/main/java/kr/co/imguru/domain/like/repository/LikeReplyRepository.java
src/main/java/kr/co/imguru/domain/like/repository/LikeReplySearchRepository.java
src/main/java/kr/co/imguru/domain/like/repository/LikeReviewRepository.java
src/main/java/kr/co/imguru/domain/like/repository/LikeReviewSearchRepository.java
src/main/java/kr/co/imguru/domain/post/controller/PostRestController.java
src/main/java/kr/co/imguru/domain/post/entity/Post.java
src/main/java/kr/co/imguru/domain/post/repository/PostSearchRepository.java
src/main/java/kr/co/imguru/domain/post/service/PostService.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java
src/main/java/kr/co/imguru/domain/reply/controller/ReplyRestController.java
src/main/java/kr/co/imguru/domain/reply/entity/Reply.java
src/main/java/kr/co/imguru/domain/reply/repository/ReplySearchRepository.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyService.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyServiceImpl.java
src/main/java/kr/co/imguru/domain/report/repository/ReportPostSearchRepository.java
src/main/java/kr/co/imguru/domain/report/repository/ReportReplySearchRepository.java
src/main/java/kr/co/imguru/domain/review/controller/ReviewRestController.java
src/main/java/kr/co/imguru/domain/review/entity/Review.java
src/main/java/kr/co/imguru/domain/review/repository/ReviewSearchRepository.java
src/main/java/kr/co/imguru/domain/review/service/ReviewService.java
src/main/java/kr/co/imguru/domain/review/service/ReviewServiceImpl.java
src/main/java/kr/co/imguru/global/model/ResponseStatus.java
src/main/resources/application.yml

1. LikePost, LikeReview, LikeReply 에 필요한 Repository, SearchRepository 생성
2. post, reply, review에 좋아요 기능 로직 생성
3. 중복 좋아요 클릭 시, 해당하는 응답 코드 추가

IG-12-jsh/like

---

build.gradle
src/main/java/kr/co/imguru/ImGuruApplication.java
src/main/java/kr/co/imguru/domain/post/service/PostService.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java
src/main/java/kr/co/imguru/global/config/RedisConfig.java
src/main/java/kr/co/imguru/global/config/SecurityConfig.java
src/main/java/kr/co/imguru/global/model/ResponseErrorFormat.java
src/main/resources/application.yml

1. Redis 의존성 추가 및 설정 추가
2. RedisConfig 파일 생성
3. Redis를 사용해서 조회 수 증가하는 로직 생성
4. Spring Schduler를 사용해주기 위해서 어노테이션 추가
5. Spring Security 의존성 추가(Security의 경우 version이 3.1.x 로 올라가며 사용방식이 변경되어, 버전 직접 지정하여 의존성 추가)
6. Spring Security Config 파일 생성, Role에 따라 접근가능 한 URL은 추후 수정 필요

IG-14-jsh/redis,security

---

build.gradle
src/main/java/kr/co/imguru/global/aop/MethodLoggingAspect.java

1. AOP dependency 추가
2. 서비스 시간과 예외 정보에 대한 로깅 출력

IG-16-jsh/aop

---

src/main/java/kr/co/imguru/domain/guru/service/GuruInfoServiceImpl.java
src/main/java/kr/co/imguru/domain/member/controller/MemberRestController.java
src/main/java/kr/co/imguru/domain/member/repository/MemberRepository.java
src/main/java/kr/co/imguru/domain/member/service/MemberService.java
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/domain/message/service/MessageServiceImpl.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyServiceImpl.java
src/main/java/kr/co/imguru/domain/report/service/ReportPostServiceImpl.java
src/main/java/kr/co/imguru/domain/report/service/ReportReplyServiceImpl.java
src/main/java/kr/co/imguru/domain/review/service/ReviewServiceImpl.java
src/main/java/kr/co/imguru/global/config/SecurityConfig.java
src/main/java/kr/co/imguru/global/model/ResponseStatus.java
src/test/java/kr/co/imguru/dummy/DummyDataTest.java

1. dummy data 생성 코드 작성 -> 추후 더 작성이 필요
2. password 암호화 위해서 passwordEncoder Bean 등록
3. member 에 비밀번호 암호화 적용 및 예외 처리 코드 추가
4. member에서 모든 일반 사용자, 전문가를 조회하는 API 추가
5. 모든 서비스에서 toEntity 시, 불필요하게 한번 더 쿼리를 실행하던 부분 수정

IG-13-jsh/refactor

---

build.gradle
src/main/java/kr/co/imguru/domain/member/controller/MemberRestController.java
src/main/java/kr/co/imguru/domain/member/dto/MemberLoginDto.java
src/main/java/kr/co/imguru/domain/member/dto/MemberReadDto.java
src/main/java/kr/co/imguru/domain/member/repository/MemberRepository.java
src/main/java/kr/co/imguru/domain/member/service/MemberService.java
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/global/auth/CustomUserDetails.java
src/main/java/kr/co/imguru/global/auth/JpaUserDetailsService.java
src/main/java/kr/co/imguru/global/auth/JwtAuthenticationFilter.java
src/main/java/kr/co/imguru/global/auth/JwtProvider.java
src/main/java/kr/co/imguru/global/config/SecurityConfig.java
src/main/resources/application.yml

1. login api 추가
2. jwt 사용을 위해 dependency와 application.yml에 secret key 값 추가.
-> secret key 는 추후 보안을 위해 안보이게 설정 필요
3. login 성공 시, token 정보를 넘겨주기 위해서 readDtoWithToken을 추가
4. jwt를 이용한 인증 로직 추가
5. security config 에서 권한에 맞게 접근 가능하도록 추후 수정이 필요.

IG-18-jsh/login,jwt

---

front/package-lock.json
front/package.json
front/src/App.vue
front/src/assets/common.css
front/src/components/PageFooter.vue
front/src/components/PageHeader.vue
front/src/main.js
front/src/router/index.js
front/src/views/PageAbout.vue
front/src/views/PageHome.vue
front/src/views/post/PostList.vue
front/vue.config.js
src/main/java/kr/co/imguru/global/config/SecurityConfig.java
src/main/java/kr/co/imguru/global/config/WebConfig.java
src/main/resources/application.yml

1. vue 초기 설정 완료
2. vue 연동 되는지 확인 위한 post list 출력
3. 연동 테스트를 위해서 SecurityConfig에서 post에 접근 권한 모두 허용으로 변경

IG-19-jsh/front-vue

---

front/public/index.html
front/src/assets/common.css
front/src/views/common/PageHome.vue
front/src/views/post/PostList.vue
src/main/java/kr/co/imguru/domain/post/controller/PostRestController.java
src/main/java/kr/co/imguru/domain/post/dto/PostReadDto.java
src/main/java/kr/co/imguru/domain/post/repository/PostRepository.java
src/main/java/kr/co/imguru/domain/post/repository/PostSearchRepository.java
src/main/java/kr/co/imguru/domain/post/service/PostService.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java

1. 페이징 처리 및 검색 가능
2. front post 목록 페이지 처리

IG-24-jsh/front-post

---

src/main/java/kr/co/imguru/domain/member/controller/MemberRestController.java
src/main/java/kr/co/imguru/domain/member/dto/MemberReadDto.java
src/main/java/kr/co/imguru/domain/member/service/MemberService.java
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/global/auth/Token.java
src/main/java/kr/co/imguru/global/auth/TokenDto.java
src/main/java/kr/co/imguru/global/auth/TokenRepository.java

1. refreshToken redis에 저장되도록 설정
2. refreshToken으로 accessToken 재발급 받는 로직 및 검사 로직 추가, refreshToken 생성 로직 추가

IG-25-jsh/refreshToken

---

front/src/assets/common.css
front/src/components/PageHeader.vue
front/src/views/common/LoginMember.vue
front/src/views/common/PageHome.vue
front/src/views/post/PostDetail.vue
front/src/views/post/PostList.vue
front/src/views/post/PostWrite.vue
front/src/vuex/store.js
src/main/java/kr/co/imguru/domain/member/controller/MemberRestController.java
src/main/java/kr/co/imguru/domain/member/service/MemberService.java
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/domain/post/controller/PostRestController.java
src/main/java/kr/co/imguru/domain/post/repository/PostSearchRepository.java
src/main/java/kr/co/imguru/domain/post/service/PostService.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java
src/main/java/kr/co/imguru/domain/reply/controller/ReplyRestController.java
src/main/java/kr/co/imguru/domain/reply/dto/ReplyReadDto.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyService.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyServiceImpl.java
src/main/java/kr/co/imguru/domain/skill/controller/SkillRestController.java
src/main/java/kr/co/imguru/domain/skill/repository/SkillRepository.java
src/main/java/kr/co/imguru/domain/skill/service/SkillService.java
src/main/java/kr/co/imguru/domain/skill/service/SkillServiceImpl.java

1. front에 댓글 연동
2. 로그인 시 token을 통해 체크하는 로직 추가
3. 수정이나 삭제, 등록 시 로그인이 되어있지 않으면 막는 로직 및 로그인한 사용자와 일치하는 경우만 동작 하도록 로직 수정

IG-27-jsh/front-post,reply

---

front/src/router/index.js
front/src/views/member/GuruInfoWrite.vue
front/src/views/member/MemberGuruDetail.vue
front/src/views/member/MemberGuruView.vue
front/src/views/member/MemberMain.vue
front/src/views/member/MemberUserDetail.vue
front/src/views/member/MemberUserView.vue
front/src/views/member/MemberView.vue
front/src/views/post/PostDetail.vue
front/src/views/post/PostList.vue
src/main/java/kr/co/imguru/domain/guru/controller/GuruInfoRestController.java
src/main/java/kr/co/imguru/domain/guru/entity/GuruInfo.java
src/main/java/kr/co/imguru/domain/guru/repository/GuruInfoSearchRepository.java
src/main/java/kr/co/imguru/domain/guru/service/GuruInfoService.java
src/main/java/kr/co/imguru/domain/guru/service/GuruInfoServiceImpl.java
src/main/java/kr/co/imguru/domain/member/controller/MemberRestController.java
src/main/java/kr/co/imguru/domain/member/dto/MemberUpdateDto.java
src/main/java/kr/co/imguru/domain/member/entity/Member.java
src/main/java/kr/co/imguru/domain/member/service/MemberService.java
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/domain/post/controller/PostRestController.java
src/main/java/kr/co/imguru/domain/post/service/PostService.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java
src/main/java/kr/co/imguru/domain/reply/controller/ReplyRestController.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyService.java
src/main/java/kr/co/imguru/domain/reply/service/ReplyServiceImpl.java

1. 마이페이지, 프로필 조회, 도사 정보 기입 조회 front 추가
2. 해당 front 에 맞는 API 추가
3. token을 사용하여 로그인한 사용자로 조회하는 API 들 memer, post, reply, guruInfo 에 추가
4. 회원 정보 수정 시, 암호화 되지 않던 pw 수정

IG-28-jsh/front-mypage

---

build.gradle
front/public/index.html
front/src/router/index.js
front/src/views/pay/PayTest.vue
src/main/java/kr/co/imguru/ImGuruApplication.java
src/main/java/kr/co/imguru/domain/pay/controller/PayRestController.java
src/main/java/kr/co/imguru/domain/pay/controller/RestPayController.java
src/main/java/kr/co/imguru/domain/pay/dto/PayApprovDto.java
src/main/java/kr/co/imguru/domain/pay/dto/PayCancelDto.java
src/main/java/kr/co/imguru/domain/pay/dto/PayCreateDto.java
src/main/java/kr/co/imguru/domain/pay/entity/Pay.java
src/main/java/kr/co/imguru/domain/pay/repository/PayRepository.java
src/main/java/kr/co/imguru/domain/pay/service/PayService.java
src/main/java/kr/co/imguru/domain/pay/service/PayServiceImpl.java
src/main/java/kr/co/imguru/global/config/JasyptConfig.java
src/main/java/kr/co/imguru/global/util/ChiperUtil.java
src/main/java/kr/co/imguru/global/util/DateUtil.java
src/main/java/kr/co/imguru/global/util/SignatureUtil.java
src/main/resources/application.yml

IG-33-jsh/pay

---

src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/domain/post/service/PostServiceImpl.java
src/main/java/kr/co/imguru/global/config/RedisConfig.java

1. reids 서버 실행되지 않거나, 오류 발생해도 웹 서비스 제공 가능하도록 예외 처리 로직 추가

IG-34-jsh/redis

---

front/src/components/PageHeader.vue
front/src/router/index.js
front/src/views/pay/PayIndex.vue
src/main/java/kr/co/imguru/domain/pay/controller/PayController.java
src/main/java/kr/co/imguru/domain/pay/controller/RestPayController.java

IG-36-jsh/pay

---

front/src/assets/common.css
front/src/views/common/JoinGuru.vue
front/src/views/common/JoinMember.vue
front/src/views/common/LoginMember.vue
front/src/views/message/MessageWrite.vue
front/src/views/pay/PayCallback.vue
front/src/views/pay/PayIndex.vue
front/src/views/post/PostDetail.vue
front/src/views/post/PostList.vue
front/src/views/post/PostWrite.vue
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/global/common/PostCategory.java

Revert "IG-37-jsh/refactor"

---

front/package-lock.json
front/package.json
front/src/assets/common.css
front/src/views/common/JoinGuru.vue
front/src/views/common/JoinMember.vue
front/src/views/common/LoginMember.vue
front/src/views/message/MessageWrite.vue
front/src/views/pay/PayCallback.vue
front/src/views/pay/PayIndex.vue
front/src/views/post/PostDetail.vue
front/src/views/post/PostList.vue
front/src/views/post/PostWrite.vue
package-lock.json
src/main/java/kr/co/imguru/domain/member/service/MemberServiceImpl.java
src/main/java/kr/co/imguru/global/common/PostCategory.java

refactor: 파일 오류로 인해 재커밋
